#!/usr/bin/env bash
# Report / declare THIS machine's identity & role in the shared ticket-docs/KG
# workflow, with LIVE verification (creds resolve? bucket reachable? mount present?).
#
#   ./identity.sh           # print a live status card
#   ./identity.sh --write    # (re)generate IDENTITY.md for Cursor (AGENTS.md) / agents to read
#
# IDENTITY.md is machine-local: gitignored (under data/), not synced, not zipped.
set -uo pipefail
cd "$(dirname "$0")"
source ./config.env

ENVN="corporate"; [[ "$BUCKET" == *poc* ]] && ENVN="poc"
HOST="$(hostname -s 2>/dev/null || echo unknown)"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ROLE_UP="$(printf '%s' "$MACHINE_ROLE" | tr '[:lower:]' '[:upper:]')"

# --- live checks -----------------------------------------------------------
ACCOUNT="$(aws sts get-caller-identity --profile "$PROFILE" --query Account --output text 2>/dev/null || echo UNAVAILABLE)"
MOUNT="absent"; command -v mount-s3 >/dev/null 2>&1 && MOUNT="$(mount-s3 --version 2>&1)"
# head-bucket = true reachability/authorization (works even when the prefix is
# empty, unlike `s3 ls` on an empty prefix which returns non-zero).
BUCKET_OK="no";  aws s3api head-bucket --bucket "$BUCKET" --profile "$PROFILE" >/dev/null 2>&1 && BUCKET_OK="yes"
DATA_OK="no";    [[ -d "$LOCAL_DATA" ]] && DATA_OK="yes"

print_card() {
cat <<EOF
+- machine identity --------------------------------------
| machine     : $MACHINE_NAME  (host $HOST)
| role        : $ROLE_UP
| environment : $ENVN
| S3 target   : s3://$BUCKET/$PREFIX   (profile $PROFILE, $REGION)
| AWS account : $ACCOUNT
| bucket read : $BUCKET_OK
| local data  : $DATA_OK   ($LOCAL_DATA)
| mount-s3    : $MOUNT
+--------------------------------------------------------
EOF
}

if [[ "${1:-}" == "--write" ]]; then
  if [[ "$MACHINE_ROLE" == "publisher" ]]; then
    RULES='You are the **KG PUBLISHER** for this workflow (Cursor primary).
- You OWN the KG publish cycle: `./data-pull.sh --go` -> kg-refresh skill / `kg_refresh.sh` -> `./data-push.sh --go`.
- You are the ONLY machine that writes `knowledge-graph/` to the bucket.
- You MAY run `--delete` housekeeping (deliberately, right after a fresh pull).
- Full procedure + role transfer: PUBLISHER_RUNBOOK.md.
- Orientation: repo root `AGENTS.md` points at this file.'
  else
    RULES='You are a **CONTRIBUTOR** in this workflow (Cursor primary).
- You MAY: pull/push ticket docs under `changes/`, read the KG with the Cursor **kg** skill (`scripts/kg_query.ps1` / `kg_query.sh`).
- You MUST NOT: push `knowledge-graph/` — only the publisher does.
- You MUST NOT: run KG rebuild/publish or `data-push --delete` (publisher-only).
- To request a rebuild: `kg_refresh.sh request "why"` then push.
- Write via `./data-push.sh`; read the shared hub via the read-only mount.
- Orientation: repo root `AGENTS.md` points at this file.'
  fi
  cat > IDENTITY.md <<EOF
# THIS MACHINE — identity & role

> Auto-generated by \`./identity.sh --write\`. Machine-local: gitignored, not
> synced, not zipped. Re-run after any \`config.env\` change. Do not hand-edit.
> Cursor reads this via root \`AGENTS.md\` / \`.cursor/rules\` every session.

- **Machine:** $MACHINE_NAME  (host \`$HOST\`)
- **Role:** $ROLE_UP
- **Environment:** $ENVN
- **S3 target:** \`s3://$BUCKET/$PREFIX\`  (profile \`$PROFILE\`, region \`$REGION\`)
- **AWS account (live):** $ACCOUNT
- **Bucket reachable (live):** $BUCKET_OK
- **Local data present:** $DATA_OK  (\`$LOCAL_DATA\`)
- **mount-s3:** $MOUNT
- **Generated:** $STAMP

## Agent instructions for this machine
$RULES

## Workflow docs
Shared-record: Confluence **Shared record (S3 sync)** / package \`START_HERE.md\`.
Cursor map: repo root \`AGENTS.md\`.
EOF
  echo "wrote $(pwd)/IDENTITY.md"; echo
fi

print_card
